"""Inject the house scan into the visor's data block.

    python -m sim.export_house_3d --write     # 1. regenerate the scan
    python samples/inject_visor_data.py       # 2. push it into the visor

The visor is a standalone page — it can't fetch a JSON file, so the pipeline
output is embedded between the HOUSE markers in propwash_visor.html. Running this
after an export keeps the visor honest: what the operator sees is what the
pipeline produced, byte for byte.
"""

from __future__ import annotations

import json
from pathlib import Path

SAMPLES = Path(__file__).resolve().parent
DATA_PATH = SAMPLES / "house_3d.json"
VISOR_PATH = SAMPLES / "propwash_visor.html"

BEGIN = "// ==HOUSE:BEGIN== generated by sim/export_house_3d.py — do not hand-edit"
END = "// ==HOUSE:END=="


def main() -> None:
    data = json.loads(DATA_PATH.read_text())
    html = VISOR_PATH.read_text()

    start = html.find(BEGIN)
    end = html.find(END)
    if start < 0 or end < 0:
        raise SystemExit(f"markers not found in {VISOR_PATH}")

    block = f"{BEGIN}\nconst HOUSE = {json.dumps(data, separators=(',', ':'))};\n"
    VISOR_PATH.write_text(html[:start] + block + html[end:])
    print(f"injected {DATA_PATH.name} into {VISOR_PATH.name}  {data['counts']}")


if __name__ == "__main__":
    main()
